
import { Button, TabWidget } from "std-widgets.slint";
import { LinkText } from "components/LinkText.slint";
import { Home } from "views/Home.slint";
import { Counter } from "views/Counter.slint";
import { HttpRequest } from "views/HttpRequest.slint";


export component AppWindow inherits Window {
    private property<int> tabIndex: 0;
    in-out property<[int]> size;
    in-out property<[int]> maxSize;

    callback homeInitCallback;
    callback httpFetchCallback(string) -> string;
    callback drawChartCallback();

    default-font-size: 16px;

    min-width: size[0] * 1px;
    min-height: size[1] * 1px;
    max-width: maxSize[0] * 1px;
    max-height: maxSize[1] * 1px;
    title: "Slint Python Template";

    VerticalLayout {
        spacing: 5px;

        HorizontalLayout {
            horizontal-stretch: 1;

            LinkText {
                text: "Home";
                onClick => {
                    root.tabIndex = 0;
                }
            }

            LinkText {
                text: "Counter";
                onClick => {
                    root.tabIndex = 1;
                }
            }

            LinkText {
                text: "HttpRequest";
                width: 100px;
                onClick => {
                    root.tabIndex = 2;
                }
            }

            LinkText {
                text: "Chart";
                onClick => {
                    root.tabIndex = 3;
                }
            }
        }

        if tabIndex == 0: Home {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            initCallback => {
                homeInitCallback();
            }
        }

        if tabIndex == 1: Counter {
            horizontal-stretch: 1;
            vertical-stretch: 1;
        }

        if tabIndex == 2: HttpRequest {
            horizontal-stretch: 1;
            vertical-stretch: 1;

            fetchCallback(url) => {
                return httpFetchCallback(url);
            }
        }

        if tabIndex == 3: Image {
            init => {
                root.drawChartCallback();
                self.source = @image-url("charts/chart.svg");
            }
        }
    }
}
